schema:
  format:
    openapi: "3.0.0"
  service_input_type: "WorkerServiceInput"

  types:
    WorkerServiceInput:
      type: object
      description: "Input properties for a Worker Fargate service"
      properties:
        desired_count:
          type: number
          description: "The default number of Fargate tasks you want running"
          default: 1
          minimum: 1
        task_size:
          type: string
          description: "The size of the task you want to run"
          enum: ["x-small", "small", "medium", "large", "x-large"]
          default: "x-small"
        image:
          type: string
          description: "The name/url of the container image"
          default: "public.ecr.aws/z9d2n7e1/nginx:1.21.0"
          minLength: 1
          maxLength: 200
