AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a Backend service on AWS Fargate, hosted in a public or private subnet, 
             and accessible via Service Discovery.
Mappings:
  TaskSize:
    medium:
      cpu: 1 vCPU
      memory: 2048
    large:
      cpu: 2 vCPU
      memory: 4096

Resources:
  ServiceAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
        Version: "2012-10-17"
      Policies:
        - PolicyName: 'Publish2SNS'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action: 'sns:Publish'
                Resource: '{{environment.outputs.SNSTopic}}'
  ServiceAccessRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: ecr:GetAuthorizationToken
            Effect: Allow
            Resource: "*"
          - Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":ecr:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :repository/aws-cdk/assets
        Version: "2012-10-17"
      PolicyName: ServiceAccessRoleDefaultPolicy
      Roles:
        - Ref: ServiceAccessRole
  Service:
    Type: AWS::AppRunner::Service
    Properties:
      SourceConfiguration:
        ImageRepository:
          ImageConfiguration:
            Port: '{{service_instance.inputs.port}}'
            RuntimeEnvironmentVariables:
              - Name: SNS_TOPIC_ARN
                Value: '{"ping":"{{environment.outputs.SNSTopic}}"}'
          ImageIdentifier: '{{service_instance.inputs.image}}'
          ImageRepositoryType: ECR_PUBLIC
      InstanceConfiguration:
        Cpu: !FindInMap [TaskSize, {{service_instance.inputs.task_size}}, cpu]
        Memory: !FindInMap [TaskSize, {{service_instance.inputs.task_size}}, memory]
      NetworkConfiguration:
        EgressConfiguration:
          EgressType: VPC
          VpcConnectorArn: '{{environment.outputs.VpcConnectorArn}}'
Outputs:
  AppRunnerServiceARN:
    Value:
      Fn::GetAtt:
        - Service
        - ServiceArn
  AppRunnerServiceURL:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Fn::GetAtt:
              - Service
              - ServiceUrl


